CC = gcc 		# le compilateur a utiliser
CFLAGS = -Wall		# les options du compilateur
LDFLAGS = -lsx		# les options pour l'editeur de liens
SRC = jeuMot.c callbacks.c modele.c vue.c # les fichiers sources
PROG = jeuMot	# nom de l'executable
OBJS = $(SRC:.c=.o)	# les .o qui en decoulent
.SUFFIXES: .c .o	# lien entre les suffixes

all: $(PROG)

# etapes de compilation et d'edition de liens 
#S@ la cible $^ toutes les dependances
$(PROG): $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

callbacks.o: callbacks.h modele.h
modele.o: modele.h
jeuMot.o: vue.h modele.h callbacks.h
# le lien entre .o et .c
# $< derniere dependance
%.o: %.c
	$(CC) $(CFLAGS) -c $<

#pour faire propre
.PHONY: clean
clean:
	rm -f *.o *~ core $(PROG)
